### ISSUE TITLE
 Develop the Data Input Modal

### ISSUE THREAD

**Issue by statisticsguru1** [statisticsguru1/E_learn#12]
**Objective:** 
Build a modal interface to allow users to specify their preferred data input method.

**_Tasks and subtasks_**
- [x]  Create a radioButtons control to let users choose between:
1. Uploading/pasting data.
2. Manually entering/typing data.

- [x] Add action buttons (actionButton) to launch the appropriate wizard based on the selection. 

- [x] Test conditional rendering to ensure the modal changes dynamically based on user input.
