### ISSUE TITLE
Implement the Modal Server Logic

### ISSUE THREAD

**Issue by statisticsguru1** [statisticsguru1/E_learn#14]
**Objective:**
Develop server-side logic to process data inputs and return a usable data frame.

**Tasks**

- [x] Define Reactive Values:
- [x] Define all reactive values that will be used across reactive functions.

- [x] Develop an Observe Event Function for Manual Data Entry:

1. Create an observe event function that listens to the click of the Enter/Type Data button and launches the JExcel data module UI. This module will allow users to input data in a spreadsheet format and specify custom column names.

- [x] Develop an Observe Event Function for Data Submission:

1. Implement an observe event function that listens for the user’s submission of the data, retrieves the data from the JExcel data module, cleans it, and makes it available as a reactive function.

- [x] Develop an Observe Event Function for File Upload or Paste Data:

1. Create an observe event function that listens to the click of the Upload File/Paste Data button and launches the datamods data input module for uploading or pasting data.

- [x] Create a Reactive Function to Determine the Input Method:

1. Develop a reactive function that identifies the chosen data input method and listens for the uploaded data. This function will make the uploaded or manually entered data available as output.
