### ISSUE TITLE
Paired sample t - test 

### ISSUE THREAD

**Issue by statisticsguru1** [statisticsguru1/E_learn#2]
This issue focuses on developing a Paired-Sample T-Test Calculator for the T-Test Calculators Module. The following tasks and subtasks outline the components required for implementation:

**Tasks and Subtasks**
**_1. Hypothesis_**

- [x]  Modify the previously developed hypothesis function (from the One-Sample T-Test) to accommodate the Paired-Sample T-Test by adding an argument for t-type and incorporating logic to generate the appropriate hypothesis statement.
- [x]  Update the explanation generator function (developed for the One-Sample T-Test) for hypothesis testing to accommodate the Paired-Sample T-Test by adding an argument for t-type and logic to generate explanations specific to the Paired-Sample T-Test.
- [x]  Ensure that both outputs can be concatenated into R Markdown for reporting, as done for the One-Sample T-Test.

 
 
 **_2. Summary Statistics_**

- [x]  Since Paired-Sample T-Tests are essentially One-Sample T-Tests for paired differences, the previously developed summary statistics functions can handle this requirement without additional modification.

**_3. Assumptions_**

- [x]  Modify the previous explanation generator for summary statistics to clarify that the sample involves paired differences.

**_4. Test Statistic_**
 

- [x] Update the explanation generator for test statistics to specify that the sample involves paired differences.

**_5. Decision_**

- [x]  Modify the previous explanation generator for the decision step to specify that the sample involves paired differences. This involves adding a modifier function to replace the One-Sample T-Test explanation with a more specialized version tailored to the Paired-Sample T-Test.
