### ISSUE TITLE
Student t probability calculator

### ISSUE THREAD

**Issue by statisticsguru1** [statisticsguru1/E_learn#4]
This issue involves developing a Student T-Calculator, which can compute lower tail, upper tail, and two-tailed probabilities for t, given the tail, mean, standard deviation, degrees of freedom, and whether the area is between or outside for two-tailed probabilities.
The calculator can compute critical values if probabilities are provided, and it reacts to changes in each output.

**Tasks and Subtasks**
**_1. Probability/Critical Values Calculations_**

- [x] Since R provides functions to compute probabilities (pt, dt, qt), there is no need to create such functions. Most of the tasks involve dealing with reactive variables (inputs and outputs), so these will be handled in another issue.

**_2. Explanation Generator_**

- [x] Develop explanation generators to show step-by-step calculations of the probabilities and critical values given the tails, mean, standard deviation, degrees of freedom, and other necessary inputs. These functions will be used within the reactive functions on the module's server side.
**_3. Critical Area Curves_**

- [x] Reuse previously developed functions for visualizing critical values in one-sample and independent-sample t-tests with minor adjustments to accommodate the reactive context in this module.
