### ISSUE TITLE
T confidence interval

### ISSUE THREAD

**Issue by statisticsguru1** [statisticsguru1/E_learn#5]
This issue involves developing a T confidence interval Calculator, which can fit a lower tail, upper tail, and two-tailed Confidence Interval for t, given the tail, summary stats (mean, standard deviation, n, CL)  or the raw data are provided, and it reacts to changes in each output.

**Tasks and Subtasks**
**_1. Confidence Interval  Calculations_**

- [x] Most of these calculations will be handled within the reactive functions since they are few.

**_2. Explanation Generator_**

- [x] Develop explanation generators to show step-by-step calculations of the CI given the tails, mean, standard deviation, degrees of freedom, and other necessary inputs. These functions will be used within the reactive functions on the module's server side.
**_3. Critical Area Curves_**

- [x] Reuse previously developed CI functions for visualizing values in one-sample and independent-sample t-tests with minor adjustments to accommodate the reactive context in this module.
