### ISSUE TITLE
Create The Module UI

### ISSUE THREAD

**Issue by statisticsguru1** [statisticsguru1/E_learn#8]
This issue involves designing a user interface (UI) for the module. Conditional input logic will dynamically adjust input options based on the selected test type and data type. At the top of the UI, there will be fields for "Test Type" and "Data Type" to guide the selection of the calculator and how the user intends to supply inputs (either as summary statistics or a dataset).

**Tasks and Subtasks**
**_1. One-Sample T-Test_**

- [x]  Design a UI for the one-sample t-test that accepts the required summary statistics.
- [x]  Provide an option to use a dataset instead of summary statistics. If selected, present a data input wizard that launches a data input 

modal.
**_2. Paired-Sample T-Test_**
 

- [x] Design a UI for the paired-sample t-test that accepts the required summary statistics.
- [x]  Provide an option to use a dataset instead of summary statistics. If selected, present a data input wizard that launches a data input modal.

**_3. Independent-Sample T-Test_**

- [x]  Design a UI for the independent-sample t-test that accepts the required summary statistics.
- [x]  Provide an option to use a dataset instead of summary statistics. If selected, present a data input wizard that launches a data input modal.

**_4. T Confidence Interval_**

- [x]  Design a UI for calculating T confidence intervals that accepts the required summary statistics.
- [x]  Provide an option to use a dataset instead of summary statistics. If selected, present a data input wizard that launches a data input modal.

**_5. T-Test for Pearson Correlation_**
 

- [x] Design a UI for the t-test for Pearson correlation that accepts the necessary summary statistics.

**_6. T-Test for Regression Coefficient_**

- [x]  Design a UI for the t-test for the regression coefficient that accepts the necessary summary statistics.

**_7. Standard T Probability/Critical Values_**
 

- [x] Design a UI for inputting relevant inputs for calculating standard t probabilities or critical values based on user inputs such as tail type, mean, standard deviation, and degrees of freedom.
